name: lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Setup Biome
        uses: biomejs/setup-biome@v2.3.0

        with:
          version: latest

      - name: Run Biome
        run: biome ci .

      # - name: Run tests
      #   run: npm test
