name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linter (oxlint)
        run: bun lint:fix

      # - name: Run tests
      #   run: npm test

      - name: Build project
        run: bun run build

      - name: Deploy project
        run: bun run deploy
